### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#131]
version: 1.0.5
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1453130]

goroutine 4010 [running]:
github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge.(*stellarWallet).MonitorBridgeAccountAndMint.func1(0xc036372c40, 0x69, 0x0, 0xc0363752c0, 0x5d, 0x0, 0xc036384090, 0x2c, 0x0, 0xc03634f3b0, ...)
	/go/src/github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge/stellar.go:345 +0xff0
github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge.(*stellarWallet).StreamBridgeStellarTransactions.func1(0xc036372c40, 0x69, 0x0, 0xc0363752c0, 0x5d, 0x0, 0xc036384090, 0x2c, 0x0, 0xc03634f3b0, ...)
	/go/src/github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge/stellar.go:465 +0x75
github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge/stellar.FetchTransactions(0x1ef6018, 0xc00020fcc0, 0x2a7a080, 0xc01eb716c0, 0x38, 0x0, 0x0, 0xc01fd77df8, 0x0, 0x0)
	/go/src/github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge/stellar/stellar.go:66 +0x3b8
github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge.(*stellarWallet).StreamBridgeStellarTransactions(0xc001b95500, 0x1ef6018, 0xc00020fcc0, 0xc036350708, 0x12, 0xc01fd77f30, 0x0, 0x2f40)
	/go/src/github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge/stellar.go:468 +0x348
github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge.(*stellarWallet).MonitorBridgeAccountAndMint(0xc001b95500, 0x1ef6018, 0xc00020fcc0, 0xc0027a6fa8, 0xc001064580, 0x450596, 0xc0014806d0)
	/go/src/github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge/stellar.go:434 +0x285
github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge.(*Bridge).Start.func1(0xc02799d7a0, 0x1ef6018, 0xc00020fcc0)
	/go/src/github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge/bridge.go:248 +0x73
created by github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge.(*Bridge).Start
	/go/src/github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge/bridge.go:247 +0x20b
```

Since the container then restarts, it happens again until k8s decides to Back-off restarting the failed container.

When reverted the deployment to v1.0.2, this problem no longer occurs

**Comment by robvanmieghem** [comment]
19d65b0e1215f7811d081775ae2ff48fd3be91a4
