### ISSUE TITLE
Bridge master does not pick up a deposit

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#63]

**Comment by robvanmieghem** [comment]
I'm not receiving any transactions and after a while:

```
panic: error reading line: read tcp 172.17.0.2:39972->54.208.185.115:443: read: connection reset by peer

goroutine 5962 [running]:
github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge.(*Bridge).Start.func1(0xc002f05b90)
        /go/src/github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge/bridge.go:218 +0x97
created by github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge.(*Bridge).Start
        /go/src/github.com/threefoldfoundation/tft/bsc/bridges/stellar/api/bridge/bridge.go:216 +0x1bf
```
